### ISSUE TITLE
"ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments" encountered in the training loop

### ISSUE THREAD

**Issue by bernt73** [KGPML/Hyperspectral#15]
Hi,

I'm using TF1.3 with Cuda 8.0 and CuDNN 6.0. May I know if this error could be caused by incompatible Tensorflow version? If so, could you share with us the version of TF/Cuda/CuDnn that you used to run the code?

![image](https://user-images.githubusercontent.com/25819890/43384954-14ecc922-9412-11e8-976e-4f38d373b484.png)

**Comment by cullinap** [comment]
I get this same issue but when I am using CNN

**Comment by cullinap** [comment]
What I did to make it work was the following:
![image](https://user-images.githubusercontent.com/11068200/50375045-656f4d00-05c5-11e9-83fa-1b2b3ba50b3e.png)

**Comment by Linkersem** [comment]
after this, i met another question,do you also has this question? or could you tell me how to solve this?

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\test\CNN_G.py", line 257, in <module>
    run_training()
  File "C:\Users\Administrator\Desktop\test\CNN_G.py", line 166, in run_training
    loss = IndianPinesCNN.loss(logits, labels_placeholder)
  File "C:\Users\Administrator\Desktop\test\IndianPinesCNN.py", line 135, in loss
    logits=logits,labels=labels, name='xentropy')
  File "E:\python3.5\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2653, in sparse_softmax_cross_entropy_with_logits
    logits.get_shape()))
ValueError: Shape mismatch: The shape of labels (received (100,)) should equal the shape of logits except for the last dimension (received (225, 16)).
